# Generated by Django 2.2 on 2019-12-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caffe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caffe_id', models.ForeignKey(null=True, on_delete=True, to='caffe.Caffe')),
            ],
        ),
    ]
