# Generated by Django 2.2 on 2019-12-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caffe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='Caffe')),
                ('location_x', models.CharField(max_length=50)),
                ('location_y', models.CharField(max_length=50)),
                ('user', models.ManyToManyField(to='profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('certification', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Suitable for work'), (2, 'Suitable for romantic dating'), (3, 'Suitable for birth'), (3, 'meeting')], null=True)),
                ('desk_name', models.CharField(max_length=200)),
                ('Caffe_id', models.ForeignKey(null=True, on_delete=True, related_name='desk', to='caffe.Caffe')),
            ],
        ),
        migrations.CreateModel(
            name='Caffefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Image'), (2, '3D'), (3, 'panaroma')], null=True)),
                ('Caffe_id', models.ForeignKey(null=True, on_delete=True, related_name='Caffefile', to='caffe.Caffe')),
            ],
        ),
    ]
