# Generated by Django 2.2.4 on 2019-09-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('caffe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caffe',
            name='user',
        ),
        migrations.AddField(
            model_name='caffe',
            name='user',
            field=models.ManyToManyField(to='user.Profile'),
        ),
    ]
