# Generated by Django 2.2 on 2019-12-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caffe',
            name='location_x',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caffe',
            name='location_y',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caffe',
            name='logo',
            field=models.ImageField(null=True, upload_to='Caffe'),
        ),
        migrations.AlterField(
            model_name='desk',
            name='category',
            field=models.IntegerField(choices=[(1, 'Suitable for work'), (2, 'Suitable for romantic dating'), (3, 'Suitable for birth'), (4, 'meeting')], null=True),
        ),
    ]
