# Generated by Django 2.2 on 2019-09-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
    ]
